CREATE TABLE LETTORI
(
    CODLET       CHAR(6) NOT NULL,
    COGNOME      VARCHAR(30),
    NOME         VARCHAR(30),
    INDIRIZZO    VARCHAR(50),
    TELEFONO     VARCHAR(20),

    PRIMARY KEY (CODLET)
);
