CREATE TABLE POLIZZE
(
    COD_POLIZZA      CHAR(10)      NOT NULL,
    NOME_CLIENTE     VARCHAR(40)   NOT NULL,
    INDIRIZZO        VARCHAR(60),
    IMPORTO          DECIMAL(9,2),
    SCADENZA         DATE,
    SIGLA_AUTO       CHAR(10),
    NUM_CAVALLI      SMALLINT,

    STATO_PAGAMENTO  CHAR(1)
                     DEFAULT 'N',

    DATA_PAGAMENTO   DATE,

    PRIMARY KEY (COD_POLIZZA)
);
