CREATE TABLE ARTICOLI
(
    CODART         CHAR(6)      NOT NULL,
    DESCRIZIONE    VARCHAR(50),
    PREZZO         DECIMAL(9,2),
    ALIQUOTAIVA    DECIMAL(4,2),
    GIACENZA       INTEGER,

    PRIMARY KEY (CODART)
);
